server:
  max-http-request-header-size: 64KB

management:
  newrelic:
    metrics:
      export:
        enabled: false
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
    env:
      post:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

aeo-logging:
  exclude-routes:
    - 'actuator'
    - 'favicon'
    - 'swagger'
    - 'api-docs'
    
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui
    urls: 
    - name: api-docs
      url: /v3/api-docs
      display-name: API Doc
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
#  packages-to-scan:

spring:
  banner:
    location: classpath:static/banner.txt
  application:
    name: cms
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
    gcp:
      core:
        enabled: false
      sql:
        enabled: false
  sql:
    init:
      mode: never
      platform: postgres
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-local.xml
  datasource:
    initialization-mode: embedded
    url: jdbc:postgresql://localhost:5432/cms-app
    username: postgres
    password: pgAdmin@123

